version: '3.7'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nodejs-app

  nodejs-app:
    build: 
      context: ./nodejs-app
    container_name: nodejs-app
    working_dir: /app
    volumes:
      - ./nodejs-app:/app
    command: sh -c "wait-for mysql:3306 -- npm install && node index.js"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: people_db
    ports:
      - "3306:3306"
